### ISSUE TITLE
Error when click callback query

### ISSUE THREAD

**Issue by yasirarism** [AmanoTeam/pyrogram#7]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello, i got this error when click callback query but program still running and can catch updates from ask method but it give error in logs

### Steps to reproduce

1. User click callback query, and bot using Message.ask from pyromod
2. I can use ask method and script still running but in log i got that error

### Code example

```python
# This is sample code only
@app.on_callback_query(
    filters.regex(pattern=r"^(genstring|pyrogram|pyrogram_bot|telethon_bot|telethon)$")
)
async def callbackgenstring(bot, callback_query):
    query = callback_query.matches[0].group(1)
    if query == "genstring":
        await callback_query.answer()
        await callback_query.message.reply(
            ask_ques, reply_markup=InlineKeyboardMarkup(buttons_ques)
        )
    elif query.startswith("pyrogram") or query.startswith("telethon"):
        try:
            if query == "pyrogram":
                await callback_query.answer()
                await generate_session(bot, callback_query.message)
            elif query == "pyrogram_bot":
                await callback_query.answer(
                    "» The session generator will be of Pyrogram v2.", show_alert=True
                )
                await generate_session(bot, callback_query.message, is_bot=True)

async def generate_session(bot, msg, telethon=False, is_bot: bool = False):
    ty = "Telethon" if telethon else "Pyrogram"
    if is_bot:
        ty += " Bot"
    await msg.reply(f"» Trying to start **{ty}** session generator...")
    api_id_msg = await msg.chat.ask(
        "Please send your **API_ID** to proceed.\n\nClick on /skip for using bot's api.",
        filters=filters.text,
    )
    if await is_batal(api_id_msg):
        return
```

### Logs

```shell
[ERROR] - [03-Nov-23 12:57:38 - pyrogram.dispatcher - object bool can't be used in 'await' expression] -> [dispatcher:241]
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 238, in handler_worker
    if await handler.check(self.client, parsed_update):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pyrogram/handlers/callback_query_handler.py", line 102, in check
    await self.filters(client, query) if callable(self.filters) else True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object bool can't be used in 'await' expression
```

**Comment by yasirarism** [comment]
I have fixed this by updating source from this https://github.com/usernein/pyromod/blob/master/pyromod/listen/callback_query_handler.py, i did not have time to PR

**Comment by alissonlauffer** [comment]
I think this can be closed now, thanks!
